/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable react/no-unknown-property */
import Head from 'next/head'
import { Suspense } from 'react';
import Loading from '../components/Loading';
import Player from '../components/Player'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Quraan Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;500;700&display=swap"
        />
      </Head>
      <Suspense fallback={<Loading />}>
        <Player />
      </Suspense>
    </div>
  );
}
